In [1]:
# 1
import numpy as np

In [2]:
# 2 △
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
None


In [3]:
# 3
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4 ×
# ファイルサイズ（byte）を表示
a.size * a.itemsize

80

In [5]:
# 5 ×
print(np.info)

<function info at 0x000001AC333DD700>


In [6]:
# 6
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7
c = np.arange(10, 50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 8
d = np.arange(0, 10)
d = d[::-1]
d

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
# 9
e = np.arange(0, 9).reshape(3, 3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 10 △
# f = np.array([1,2,0,0,4,0])
# print(f[f!=0])

f = np.nonzero([1,2,0,0,4,0])
f

(array([0, 1, 4], dtype=int64),)

In [11]:
# 11
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 12
z = np.random.random([3, 3, 3])
z

array([[[0.46756986, 0.04373355, 0.7109456 ],
        [0.1025432 , 0.99652139, 0.45688543],
        [0.64835596, 0.42351865, 0.22108204]],

       [[0.34046011, 0.91119371, 0.71486412],
        [0.46908595, 0.14035667, 0.90661549],
        [0.93307179, 0.42461488, 0.36535483]],

       [[0.75819649, 0.33788229, 0.21951612],
        [0.73066634, 0.93998217, 0.09281974],
        [0.70647079, 0.89397382, 0.48544577]]])

In [13]:
# 13
z = np.random.random([10, 10])
print(f'max:{z.max()}, min:{z.min()}')

max:0.9825056111050788, min:0.0013398904433452596


In [14]:
# 14
z = np.random.random(30)
print(f'mean:{z.mean()}')

mean:0.6463842820772192


In [15]:
# 15 △
# z = np.ones(25).reshape(5, 5)
# z[1:-1, 1:-1] = 0
# z
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# 16 △
# z = np.ones(16).reshape(4, 4)
# np.pad(z, [1, 1], 'constant')
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
# 17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
# 18
# z = np.zeros(25).reshape(5,5)
# np.diag(z, k=-1)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
# 19 ×
# z = np.zeros(64).reshape(8, 8)
# z[1::2, ::2] = 1　2行目から2行おき、1列目から2列おきの要素を1にする。
# z[::2, 1::2] = 1　1行目から2行おき、2列目から2列おきの要素を1にする。
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
# 20 ×
# z = np.arange(1, 6*7*8+1).reshape(6, 7, 8)
# z[1, 5, 3]
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [21]:
# 21
z = np.eye(2)
np.tile(z, [4, 4])

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [22]:
# 22 △
# np.random.randn(25).reshape(5,5)
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.28240898 -0.3692317   1.47710424 -1.27794367 -1.38531952]
 [ 0.16477261  0.88469534 -0.6446743  -0.14919864  0.9451458 ]
 [ 1.34093689  0.53099509 -0.20598569  1.84296109 -1.83246099]
 [ 1.09256817 -1.15282255 -0.91799417 -1.28980432  0.74817892]
 [ 0.34797439 -0.12698865 -0.8003194  -0.21298633  1.27280637]]


In [23]:
# 23 ×
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [24]:
# 24
a = np.random.random((5, 3))
b = np.random.random((3, 2))
a.dot(b)

array([[0.30949846, 0.34575816],
       [0.48681859, 0.67170071],
       [0.20887907, 0.50091242],
       [0.64425412, 0.92065151],
       [0.47631837, 0.80401826]])

In [25]:
# 25 
# z = np.random.randint(0, 9, 10)
# print(z)
# z[(z >= 3) & (z <= 8)] = 0
# z
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [26]:
# 26
print(sum(range(5), -1))
print(np.sum(range(5), -1))

9
10


In [27]:
# 27
z = np.arange(5)
print(z)
print(z ** z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
print(z<z>z)

[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# 28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

In [28]:
# 29
z = np.random.random(5)
z.round()
# Z = np.random.uniform(-10,+10,10)
# print(np.copysign(np.ceil(np.abs(Z)), Z))

array([0., 0., 1., 1., 0.])

In [29]:
# 30 ×
a = np.random.randint(0, 9, 10)
print(a)
b = np.random.randint(0, 9, 10)
print(b)
# c = a & b
# print('c: ', c[c!=0])

print(np.intersect1d(a, b))

[2 6 4 6 4 1 1 2 2 4]
[3 5 1 0 5 2 6 8 2 4]
[1 2 4 6]


In [30]:
# 31 ×
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

In [31]:
# 32
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


In [32]:
# 33 △
import datetime
today = datetime.date.today()
# yesterday = today - datetime.timedelta(days=1)
# tomorrow = today + datetime.timedelta(days=1)

print(np.datetime64(today) - np.timedelta64(1))
print(np.datetime64(today) + np.timedelta64(1))

print(np.datetime64('today'))

2022-03-28
2022-03-30
2022-03-29


In [33]:
# 34
np.arange('2016-07', '2016-08', np.timedelta64(1,'D'), dtype='datetime64')

# Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
# print(Z)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [34]:
# 35　△
A = np.arange(0,9)
B = np.arange(0,9)
# A = np.ones(3)*1
# B = np.ones(3)*2
((A + B)*(-A / 2))

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [35]:
# 36　×
z = np.random.uniform(0, 10, 10)

print(z - z%1)
print(z // 1)
print(np.floor(z))
print(z.astype(int))
print(np.trunc(z))

[0. 8. 6. 2. 7. 8. 1. 1. 0. 8.]
[0. 8. 6. 2. 7. 8. 1. 1. 0. 8.]
[0. 8. 6. 2. 7. 8. 1. 1. 0. 8.]
[0 8 6 2 7 8 1 1 0 8]
[0. 8. 6. 2. 7. 8. 1. 1. 0. 8.]


In [36]:
# 37 ×
# z = np.random.random(25).reshape(5, 5)*4
# z

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# Z = np.tile(np.arange(0, 5), (5,1))
# print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [37]:
# 38　×
# z = np.random.randint(0, 9, 10)
# z

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
# 39　×
# z = np.random.random(10)
# z

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [39]:
# 40
z = np.random.random(10)
np.sort(z)

array([0.35007203, 0.36383899, 0.409516  , 0.4443816 , 0.50886116,
       0.54054958, 0.62376185, 0.96284884, 0.98615133, 0.9922569 ])

In [96]:
# 41 ×
import time
z = np.random.random(100)
time_start = time.time()
z.sum()
time_end = time.time()
print(f'{time_end - time_start} sec')

time_start =time.time()
sum = 0
for n in z:
    sum += n
time_end = time.time()
print(f'{time_end - time_start} sec')

0.0 sec
0.001001596450805664 sec


In [95]:
# 41 solution
z = np.arange(10)
# print(z.sum())
np.add.reduce(z)

45


45

In [97]:
# 42 ×
a = np.random.random(10)
b = np.random.random(10)
# a == b

equal = np.allclose(a, b)
print(equal)

False


In [57]:
# 43
z43 = np.random.random(10)
z43.flags.writeable = False
z43[0]

0.8834106052972153

In [98]:
# 44 ×
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(x, y)
print(r)
print(t)

[1.28170636 0.9272494  0.615735   0.8354684  0.93755735 1.12719527
 0.48368588 0.86130149 0.96408651 0.39819439]
[0.86956134 0.68989802 0.24779544 0.22236125 1.35145054 0.65483857
 0.68096513 0.45667312 0.50377578 1.49632793]


In [63]:
# 45
z = np.random.random((10,1))
z[np.argmax(z)] = 0
z

array([[0.19458848],
       [0.51259602],
       [0.41053635],
       [0.15426807],
       [0.        ],
       [0.29339942],
       [0.43648681],
       [0.45290728],
       [0.67907721],
       [0.09555827]])

In [100]:
# 46 △
dtype = [('x', 'i'), ('y', 'i')]
z = np.zeros(2, dtype=dtype) 
z['x'] = [0,1]
z['y'] = [0,1]
z

array([(0, 0), (1, 1)], dtype=[('x', '<i4'), ('y', '<i4')])

In [101]:
# 46 solution
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [127]:
# 47
# X = np.random.random(5)
# Y = np.random.random(5)
# X = np.tile(X, [5, 1])
# Y = np.tile(Y, [5, 1])
# C = 1 / (X - Y)
# C

x = np.arange(1, 4)
y = x + 3
print(x, y)
test = np.subtract(x, y)
print(test)
print(np.outer(x, test))
print(np.subtract.outer(x, y))
c = 1.0 / np.subtract.outer(x, y)
c

[1 2 3] [4 5 6]
[-3 -3 -3]
[[-3 -3 -3]
 [-6 -6 -6]
 [-9 -9 -9]]
[[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]


array([[-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

In [102]:
# 47 solution
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [76]:
# 48
ii64 = np.iinfo(np.int64)
print(ii64.max)
fi64 = np.finfo(np.float64)
print(fi64.max)

9223372036854775807
1.7976931348623157e+308


In [128]:
# 48 solution
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [87]:
# 49
z = np.random.random(10)
np.set_printoptions(floatmode="maxprec")
z

array([0.24198646, 0.37465378, 0.00396514, 0.54245403, 0.12300198,
       0.41136517, 0.39861761, 0.97690668, 0.02700176, 0.61880643])

In [129]:
# 49 solution
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [91]:
# 50 ×
z = np.random.random(20)
z[np.argmin(z[z > 0.5])]

0.36576607423227014

In [131]:
# 50 solution
# 任意の数との差が最も小さくなる数を取得している。
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

83
83.07726835171783


In [165]:
# 51 △
Z = np.zeros((1,1), [('position',[('x',float),('y',float)]), ('color',[('r',int),('g',int),('b',int)])])
Z

array([[((0., 0.), (0, 0, 0))]],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<i4'), ('g', '<i4'), ('b', '<i4')])])

In [153]:
# 52
z = np.zeros((100, 1), [('x',float),('y',float)])
z['x'] = np.arange(0,100).reshape(100, 1)
z['y'] = np.random.random((100, 1))
dist = np.sqrt(z['x']**2 + z['y']**2)
dist

array([[ 0.74344779],
       [ 1.29579252],
       [ 2.06280547],
       [ 3.00036285],
       [ 4.04736346],
       [ 5.00669716],
       [ 6.07182537],
       [ 7.00345708],
       [ 8.03629118],
       [ 9.0149478 ],
       [10.00017564],
       [11.00247669],
       [12.00004225],
       [13.01311512],
       [14.00000425],
       [15.0000052 ],
       [16.02259891],
       [17.00025579],
       [18.00000073],
       [19.01086511],
       [20.02009549],
       [21.01505489],
       [22.00015028],
       [23.01437919],
       [24.01092982],
       [25.00723678],
       [26.01705036],
       [27.00943695],
       [28.00928398],
       [29.01014885],
       [30.00364278],
       [31.01265801],
       [32.00998728],
       [33.00081153],
       [34.00623002],
       [35.00020817],
       [36.0022673 ],
       [37.00097344],
       [38.00028064],
       [39.00229082],
       [40.00034147],
       [41.00663425],
       [42.01166035],
       [43.00399737],
       [44.00012602],
       [45

In [171]:
# 52 solution
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
# print(X)

[[0.90373165 0.07326989 0.24759809 0.34215326 0.38791959 0.32565293
  0.9802204  0.08738515 0.76888719 0.77606542]]


In [189]:
a = np.random.random((10, 2))
print(a)
x, y = np.atleast_2d(a[:, 0], a[:, 1])
a[:, 0]-a[:, 0].T
print(x.T)

[[0.75771899 0.35246011]
 [0.38787763 0.23966761]
 [0.73362423 0.50473383]
 [0.1493179  0.02873348]
 [0.70509728 0.19068265]
 [0.80179641 0.39831284]
 [0.08488549 0.31737952]
 [0.46976864 0.29550657]
 [0.4354563  0.02206445]
 [0.37859327 0.04024912]]
[[0.75771899]
 [0.38787763]
 [0.73362423]
 [0.1493179 ]
 [0.70509728]
 [0.80179641]
 [0.08488549]
 [0.46976864]
 [0.4354563 ]
 [0.37859327]]


In [191]:
# 53
# z = np.random.random(10)
# z.astype('float32')
# z.astype('int32')

z = (np.random.rand(10)*100).astype(np.float32)
y = z.view(np.int32)
z

array([87.49013 , 12.19686 , 51.816124, 43.591976, 89.448456, 58.318485,
       55.820816, 71.71057 , 78.85223 , 16.728624], dtype=float32)

In [194]:
# 54 △
text = """
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
"""
from io import StringIO
s = StringIO(text)

z = np.genfromtxt(s, delimiter=',', dtype=np.int)
z

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

In [197]:
# 55 ×
z = np.arange(10).reshape(2, 5)

for index, value in np.ndenumerate(z):
    print(index, value)
print('  ')
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
  
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


In [249]:
# 56 Generate a generic 2D Gaussian-like array (★★☆)
# (10, 10)の配列x, yを生成
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
# 各座標の距離を算出
D = np.sqrt(x*x+y*y)
# 正規分布
sigma, mu = 1.0, 0.0
# 
G = np.exp(-( (D-mu)**2 / (2.0 * sigma**2 )))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [216]:
# 57
z = np.random.random((10, 10))
# np.random.choice(z.reshape(1,-1))
# np.put(z, np.random.choice(z), 0)

ValueError: a must be 1-dimensional

In [251]:
# 57 solution
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [252]:
# 58
z = np.random.random((5, 5))
z_mean = z.mean(axis=1, keepdims=True)
np.subtract(z, z_mean)

[[-0.2779308   0.15575899 -0.34359667  0.46699217 -0.00122369]
 [ 0.28473751 -0.43440327 -0.06592459 -0.12999577  0.34558613]
 [ 0.28983682  0.09489194 -0.42467323 -0.3077078   0.34765228]
 [ 0.1174732   0.16576132 -0.33222986  0.31997201 -0.27097668]
 [ 0.18571852 -0.06609204  0.1746679   0.00474735 -0.29904173]]


array([[-0.2779308 ,  0.15575899, -0.34359667,  0.46699217, -0.00122369],
       [ 0.28473751, -0.43440327, -0.06592459, -0.12999577,  0.34558613],
       [ 0.28983682,  0.09489194, -0.42467323, -0.3077078 ,  0.34765228],
       [ 0.1174732 ,  0.16576132, -0.33222986,  0.31997201, -0.27097668],
       [ 0.18571852, -0.06609204,  0.1746679 ,  0.00474735, -0.29904173]])

In [254]:
# 59
z = np.random.randint(0,10, 20)
z = z.reshape(5, 4)
print(z)
z[z[:, 2].argsort(), :]
# z[z[:, 2].argsort()] 同じ

[[6 4 6 1]
 [5 9 4 9]
 [7 7 3 1]
 [0 6 6 4]
 [1 6 5 5]]


array([[7, 7, 3, 1],
       [5, 9, 4, 9],
       [1, 6, 5, 5],
       [6, 4, 6, 1],
       [0, 6, 6, 4]])

In [244]:
# 60
z = (np.arange(20).reshape(5, 4)).astype(np.float32)
z[0,1] = np.nan
np.isnan(z).any()

True

In [255]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [282]:
# 61
np.random.seed(0)
z = np.random.random(20)
num = np.random.random()
print(z, num)
z[(np.abs(z - num)).argmin()]
# z.flat[(np.abs(z - num)).argmin()] 同じ？

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215] 0.978618342232764


0.9636627605010293

In [284]:
# 62 ×
a = np.arange(3)
b = np.arange(3).reshape(3,-1)

sum = 0
for n in range(a.size):
    sum += a[n] + b[n]
sum

array([6])

In [286]:
# 62 solution
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [294]:
a = np.arange(3).reshape(3,1)
B = np.arange(3)
it = np.nditer([A,B,None])
# itのindex0の配列のindex0の要素から順に繰り返し、すべての組み合わせを出力する。
for x,y,z in it:
    print(x, y)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [272]:
# 63 ×
class Array:
    pass

attribute = Array()

In [298]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

print(Z)

range_10
[0 1 2 3 4 5 6 7 8 9]


In [301]:
# 64 ×
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
# bincount は重複する要素をカウントする関数
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 9 4 4 6 4 4 3 4 4 8 4 3 7 5 5 0 1 5 9]
[2. 2. 1. 3. 8. 5. 2. 2. 2. 3.]


In [316]:
# 65 ×
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,weights=X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [3]:
# b配列の最大値を長さとする配列（c）を作り、c[bの要素] = a[bの要素]を割り当てる
a = [0,1,2]
b = [1,2,4]
np.bincount(b, a)

array([0., 0., 1., 0., 2.])

In [17]:
# 66 ×
# Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
w, h = 3, 3
# w, h = 256, 256
# rbgの3D-Array
np.random.seed(0)
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
print(I)
# (3,3,3)の配列の各業を1列目を最優先に昇順にしている
colors = np.unique(I.reshape(-1, 3), axis=0)
print(colors)
n = len(colors)
print(n)

[[[0 3 1]
  [0 3 3]
  [3 3 1]]

 [[3 1 2]
  [0 3 2]
  [0 0 0]]

 [[2 1 2]
  [3 3 2]
  [0 1 1]]]
[[0 0 0]
 [0 1 1]
 [0 3 1]
 [0 3 2]
 [0 3 3]
 [2 1 2]
 [3 1 2]
 [3 3 1]
 [3 3 2]]
9


In [24]:
# 67 ?
z = np.random.randint(0, 4, (2, 2, 2, 2))
print(z)
np.sum(z, axis=(-2, -1))

[[[[0 0]
   [3 2]]

  [[3 2]
   [1 2]]]


 [[[3 0]
   [3 1]]

  [[1 1]
   [3 1]]]]


array([[5, 8],
       [7, 6]])

In [ ]:
# 68
